AWSTemplateFormatVersion: 2010-09-09
Resources:
  ApiProxyFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code: ./
      FunctionName: 'AWSTrainingLambdaFunction'
      MemorySize: 256
      Tags:
        - Value: SAM
          Key: 'lambda:createdBy'
      Handler: ./src/handler.handler
      Role: !GetAtt
        - ProxyApiRole
        - Arn
      Runtime: nodejs18.x
      Timeout: 30
 
  ProxyApiRole:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  ApiProxyFunctionPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      FunctionName: !Ref ApiProxyFunction

  ProxyApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Proxy API Gateway
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: 'AWSTrainingProxyApi'

  ProxyResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ProxyApi
      ParentId: !GetAtt 
        - ProxyApi
        - RootResourceId
      PathPart: '{proxy+}'
  ProxyResourceANY:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref ProxyApi
      ResourceId: !Ref ProxyResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiProxyFunction.Arn}/invocations

  ApiProxyDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ProxyApiRootMethod

  ApiProxyDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ProxyResourceANY
    Properties:
      RestApiId: !Ref ProxyApi
      StageName: 'dev'

Outputs:
  ApiUrl:
    Description: URL of the API Gateway endpoint
    Value: !Sub
      https://${ProxyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/

